### ISSUE TITLE
`mas help [(string)]` crashes `mas`

### ISSUE THREAD

**Issue by rinopo** [argon/mas#10]
Hi,
Kudos for the signin/signout commands!

I've encountered the following error on `mas help signout`.

```sh-session
$ mas help signout
Sign out of the Mac App Store

Illegal instruction: 4
```

[mas_2016-02-21-122638_mb-2014-i.crash.txt](https://github.com/argon/mas/files/139443/mas_2016-02-21-122638_mb-2014-i.crash.txt)

**Comment by argon** [comment]
Hi,

This seems to be related to older hardware. What is your machine specs. Could you please try updating to mas 1.1.2 as it has more debugging information associated so a crash log from that version would be much more useful,

Thanks

**Comment by rinopo** [comment]
Upgraded to 1.1.2 :bee: and here's the crash report: [mas_2016-02-22-002403_mb-2014-i.crash.txt](https://github.com/argon/mas/files/139706/mas_2016-02-22-002403_mb-2014-i.crash.txt)
I'm on a MacBook Pro (Retina, 13-inch, Late 2013).

The error is reporducible on my iMac (Retina 5K, 27-inch, Late 2015), too, but it doesn't yield crash on that machine (the command just exits with the error message).

```sh-session
$ mas help signout
Sign out of the Mac App Store

Illegal instruction: 4
$ echo $?
132
```

I've also noticed that the error occurs not only with `mas help signout` but also with some other subcommands, namely: `account`, `list`, `outdated`, `upgrade` and `version`.
(Edited the issue title accordingly.)
Other subcommands (`help`, `install` and `signin`) exit successfully.

**Comment by argon** [comment]
I have managed to replicate this problem with `mas help` I will do what I can to resolve this ASAP.

Thanks for the information

**Comment by argon** [comment]
This should be fixed in 1.1.3

**Comment by rinopo** [comment]
Thanks a lot!

**Comment by andrei-labin** [comment]
Hey argon! I still get the "Illegal instruction: 4" on 1.1.3. This on fairly new MacPros and a VM.
On another note: this is awesome and will save me tons of repackaging/capturing!

**Comment by argon** [comment]
Is it with `mas help` or a different command?

**Comment by andrei-labin** [comment]
actually, `mas help` is about the only command that doesn't instruct illegally. `mas version` gives 1.1.3.
tried: list, signin.
`mas upgrade` gives "Everything is up-to-date"

**Comment by argon** [comment]
Is this a fresh install?

**Comment by andrei-labin** [comment]
No, the machine had been running for a while. I'll do a fresh install and see how it goes. Thanks for the help!
